---
name: Commit Check
on:
  pull_request:
    branches: ['master']

jobs:
  commit-check:
    name: Commit Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: commit-check/commit-check-action@v1
        with:
          message: true
          author-name: true
          author-email: true
          commit-signoff: true
          job-summary: true
          pr-comments: true
